using System.IO;
using System.Text;

using UnityEditor;

using UnityEngine;

public static class LoadLevelListReload
{
    [MenuItem("Helping Hand/Levels/Sequence", false, 85)]
    public static void LoadSequence()
    {
        LoadLevelUtils.LoadCommonScenes();
    }

    [MenuItem("Helping Hand/Levels/Reload this menu", false, 100)]
    public static void Reload()
    {
        GenerateOpenSceneMenuScript();
    }

    private static void GenerateOpenSceneMenuScript()
    {
        string myPath = null;
        string[] guids = AssetDatabase.FindAssets(nameof(LoadLevelListReload));
        foreach (string guid in guids)
        {
            myPath = AssetDatabase.GUIDToAssetPath(guid);
            break;
        }

        if (myPath == null)
        {
            Debug.LogError($"[{nameof(LoadLevelListReload)}] Path for this class not found");
        }
        else
        {
            string basePath = Path.GetDirectoryName(myPath);
            string menuScriptPath = Path.Combine(basePath, $"{nameof(LoadLevelList)}.cs");

            StringBuilder sb = new StringBuilder();
            _ = sb.AppendLine("//Autogenerated class by script: " + myPath);
            _ = sb.AppendLine("using UnityEditor;");
            _ = sb.AppendLine("");
            _ = sb.AppendLine($"public static class {nameof(LoadLevelList)}");
            _ = sb.AppendLine("{");

            var sceneGUIDs = AssetDatabase.FindAssets($"t:Scene", new[] { "Assets/Scenes/Levels" });
            foreach (var sceneGUID in sceneGUIDs)
            {
                var scenePath = AssetDatabase.GUIDToAssetPath(sceneGUID);
                var sceneNameRaw = Path.GetFileNameWithoutExtension(scenePath);

                _ = sb.AppendLine("");
                _ = sb.AppendLine($"    [MenuItem(\"Helping Hand/Levels/{sceneNameRaw}\", false, 0)]");
                _ = sb.AppendLine($"    private static void Open{sceneGUID}()");
                _ = sb.AppendLine($"    {{");
                _ = sb.AppendLine($"        LoadLevelUtils.LoadLevel(\"{scenePath}\");");
                _ = sb.AppendLine($"    }}");
            }


            _ = sb.AppendLine("}");

            File.Delete(menuScriptPath);
            File.WriteAllText(menuScriptPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.ImportAsset(menuScriptPath);

            Debug.Log($"[{nameof(LoadLevelListReload)}] Menu updated");
        }
    }
}