//Autogenerated class by script: Assets/Scripts/Editor/LevelLoader/LoadLevelListReload.cs
using UnityEditor;

public static class LoadLevelList
{

    [MenuItem("Helping Hand/Levels/Matthieu 1", false, 0)]
    private static void Openeea43641e50a78d45904edaf668fe436()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Matthieu 1.unity");
    }

    [MenuItem("Helping Hand/Levels/Matthieu 2", false, 0)]
    private static void Open10093fc51f1e221459640dfc96a3e889()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Matthieu 2.unity");
    }

    [MenuItem("Helping Hand/Levels/Matthieu 3", false, 0)]
    private static void Opena5a384a7a5646d044b9903473f4180bb()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Matthieu 3.unity");
    }
}
