//Autogenerated class by script: Assets/Scripts/Editor/LevelLoader/LoadLevelListReload.cs
using UnityEditor;

public static class LoadLevelList
{

    [MenuItem("Helping Hand/Levels/Matthieu Test", false, 0)]
    private static void Open15e8b0ab92e7e7f4cb03088a83900a99()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/Matthieu Test.unity");
    }

    [MenuItem("Helping Hand/Levels/MenuTests", false, 0)]
    private static void Open97e3c7ccd5c5fa54693bbdfa4ff947dc()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/MenuTests.unity");
    }

    [MenuItem("Helping Hand/Levels/TestSequence0", false, 0)]
    private static void Open37888990636850d4bbf86fdc6aaf589e()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/TestSequence0.unity");
    }

    [MenuItem("Helping Hand/Levels/TestSequence1", false, 0)]
    private static void Openf0df0b76b66bce24395cbbb94d9435ad()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/TestSequence1.unity");
    }

    [MenuItem("Helping Hand/Levels/TestSequence2", false, 0)]
    private static void Open677a338ff646d3042b13e8f07cefedb3()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/TestSequence2.unity");
    }
}
