//Autogenerated class by script: Assets/Scripts/Editor/LevelLoader/LoadLevelListReload.cs
using UnityEditor;

public static class LoadLevelList
{

    [MenuItem("Helping Hand/Levels/0_Onboarding", false, 0)]
    private static void Openc13a3d6c6f8ba904690678345995468c()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/0_Onboarding.unity");
    }

    [MenuItem("Helping Hand/Levels/1_Acte1", false, 0)]
    private static void Openb38b1e854d66a1d4e9c9b71d90075e93()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/1_Acte1.unity");
    }

    [MenuItem("Helping Hand/Levels/Matthieu Test", false, 0)]
    private static void Open15e8b0ab92e7e7f4cb03088a83900a99()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/Matthieu Test.unity");
    }

    [MenuItem("Helping Hand/Levels/MenuTests", false, 0)]
    private static void Open97e3c7ccd5c5fa54693bbdfa4ff947dc()
    {
        LoadLevelUtils.LoadLevel("Assets/Scenes/Levels/Tests/MenuTests.unity");
    }
}
